In [1]:
import pandas as pd
import requests

In [ ]:
key = "otqvshn22qrt"
regionCode = "CL"

url = f"https://api.ebird.org/v2/ref/taxonomy/ebird"

payload={}
headers = {
  'X-eBirdApiToken': key
}
response = requests.request("GET", url, headers=headers, data=payload)

In [43]:
text = response.text

In [68]:
a = text.split("\n")
headers = a[0].split(",")
body = a[1:]

In [69]:
body_aux = []
for i in range(len(body)):
    body[i] = body[i].split(",")
    if len(body[i]) == 15:
        body_aux.append(body[i])
body = body_aux

In [73]:
df = pd.DataFrame(body, columns=headers)

In [74]:
df

,SCIENTIFIC_NAME,COMMON_NAME,SPECIES_CODE,CATEGORY,TAXON_ORDER,COM_NAME_CODES,SCI_NAME_CODES,BANDING_CODES,ORDER,FAMILY_COM_NAME,FAMILY_SCI_NAME,REPORT_AS,EXTINCT,EXTINCT_YEAR,FAMILY_CODE
0,Struthio camelus,Common Ostrich,ostric2,species,2.0,COOS,STCA,,Struthioniformes,Ostriches,Struthionidae,,,,struth1
1,Struthio molybdophanes,Somali Ostrich,ostric3,species,7.0,SOOS,STMO,,Struthioniformes,Ostriches,Struthionidae,,,,struth1
2,Struthio camelus/molybdophanes,Common/Somali Ostrich,y00934,slash,8.0,SOOS COOS,STCA STMO,,Struthioniformes,Ostriches,Struthionidae,,,,struth1
3,Rhea americana,Greater Rhea,grerhe1,species,10.0,GRRH,RHAM,,Rheiformes,Rheas,Rheidae,,,,rheida1
4,Rhea pennata,Lesser Rhea,lesrhe2,species,16.0,LERH,RHPE,,Rheiformes,Rheas,Rheidae,,,,rheida1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13747,Saltator grossus,Slate-colored Grosbeak,slcgro1,species,35127.0,SCGR,SAGR,SCOG,Passeriformes,Tanagers and Allies,Thraupidae,,,,thraup2
13748,Saltator fuliginosus,Black-throated Grosbeak,bltgro2,species,35130.0,BTGR,SAFU,,Passeriformes,Tanagers and Allies,Thraupidae,,,,thraup2
13749,Saltator sp.,saltator sp.,saltat1,spuh,35131.0,,,,Passeriformes,Tanagers and Allies,Thraupidae,,,,thraup2
13750,Passeriformes sp.,passerine sp.,passer1,spuh,35132.0,,,,Passeriformes,,,,,,
13751,Aves sp.,bird sp.,bird1,spuh,35133.0,,,UNBI,,,,,,,

In [75]:
df.to_csv("taxonomia.csv", index=False)