In [2]:
import pandas as pd
import requests

In [40]:
def anho(y):
    print(" ")
    key = "otqvshn22qrt"
    regionCode = "CL"
    payload={}
    headers = {
        'X-eBirdApiToken': key
    }
    df = pd.DataFrame()
    for m in range(1, 13):
        for d in range(1, 32):
            print(f"{d}-{m}-{y}", end=" ; ")
            url = url = f"https://api.ebird.org/v2/data/obs/{regionCode}/historic/{y}/{m}/{d}"
            response = requests.request("GET", url, headers=headers, data=payload)
            df = pd.concat([df, pd.json_normalize(response.json())], ignore_index=True)
    return df

In [ ]:
for y in range(2019, 2022):
    df = anho(y)
    df.to_csv(f"vis_{y}.csv", index=False)

In [192]:
df_2019 = pd.read_csv("vis_2019.csv")
df_2020 = pd.read_csv("vis_2020.csv")

In [47]:
df_2019

,speciesCode,comName,sciName,locId,locName,obsDt,howMany,lat,lng,obsValid,obsReviewed,locationPrivate,subId,exoticCategory,errors
0,soulap1,Southern Lapwing,Vanellus chilensis,L4026975,Loma Linda,2019-01-01 23:00,1.0,-33.435764,-71.677103,True,False,False,S51197645,NaN,NaN
1,brnowl,Barn Owl,Tyto alba,L4026975,Loma Linda,2019-01-01 23:00,1.0,-33.435764,-71.677103,True,False,False,S51197645,NaN,NaN
2,aupowl1,Austral Pygmy-Owl,Glaucidium nana,L4026975,Loma Linda,2019-01-01 23:00,1.0,-33.435764,-71.677103,True,False,False,S51197645,NaN,NaN
3,austhr1,Austral Thrush,Turdus falcklandii,L7488647,Plaza Melvin Jones,2019-01-01 22:25,1.0,-33.451996,-70.593581,True,False,False,S51194229,NaN,NaN
4,whcela1,White-crested Elaenia,Elaenia albiceps,L8346445,"1485 Loncoyen, Valdivia, Región de los Ríos, C...",2019-01-01 22:05,NaN,-39.824130,-73.278223,True,False,True,S51192610,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62676,verfly,Vermilion Flycatcher,Pyrocephalus rubinus,L760571,Azapa,2019-12-31 08:10,2.0,-18.517247,-70.197006,True,False,False,S63139126,NaN,NaN
62677,slbfin3,Slender-billed Finch,Xenospingus concolor,L760571,Azapa,2019-12-31 08:10,1.0,-18.517247,-70.197006,True,False,False,S63139126,NaN,NaN
62678,blbgra1,Blue-black Grassquit,Volatinia jacarina,L760571,Azapa,2019-12-31 08:10,1.0,-18.517247,-70.197006,True,False,False,S63139126,NaN,NaN
62679,chtsee1,Chestnut-throated Seedeater,Sporophila telasco,L760571,Azapa,2019-12-31 08:10,10.0,-18.517247,-70.197006,True,False,False,S63139126,NaN,NaN
62680,perter2,Peruvian Tern,Sternula lorata,L12031093,Hornitos,2019-12-31 07:20,1.0,-22.872257,-70.288054,True,True,True,S72204442,NaN,NaN

In [213]:
ubicaciones = df_2019[["locName", "lat", "lng"]].drop_duplicates(df_2019.columns[df_2019.columns.isin(['locName'])],
                        keep='first')

In [214]:
ubicaciones

                                                 locName        lat        lng
0                                             Loma Linda -33.435764 -71.677103
3                                     Plaza Melvin Jones -33.451996 -70.593581
4      1485 Loncoyen, Valdivia, Región de los Ríos, C... -39.824130 -73.278223
5                                     (-35.594, -71.735) -35.593632 -71.735010
6                              Poniente--Calles y Plazas -33.537781 -70.561735
...                                                  ...        ...        ...
62618                                      Laguna Rivera -39.344536 -71.688309
62634              Dientes de Navarino--Laguna Betinelli -55.047450 -67.628789
62655                   Faro San Isidro--Cruz de froward -53.832784 -71.079483
62657                Pinto, Ñuble, CL (-36.878, -71.464) -36.878458 -71.463928
62664                             humedal brisas del sol -36.741205 -73.089563

[7735 rows x 3 columns]

In [216]:
#https://nominatim.org/release-docs/develop/api/Overview/
def region(lat, lon):
    url = f'https://nominatim.openstreetmap.org/reverse?lat={lat}&lon={lon}&format=json'
    page = requests.get(url)
    json = page.json()
    region = json['address']['state']
    return region

In [217]:
ubicaciones["state"] = 0

In [218]:
ubicaciones['state'] = df_2019.apply(lambda x: region(x['lat'], x['lng']), axis=1)
ubicaciones

KeyError: 'state'